#!/usr/bin/env python3
"""Run pinned ph2dt over prepared inputs (R2 binary + fail-closed input gate)."""
import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path
from tier_outcomes import sha

EXPECTED_SHA256 = "81438e6afb045bccaf3ee27e6b2d7321834ebec81c513b29af2fe764efb63cf7"
from contract_io import load_contract
from runtime_support import binary, native_environment
BIN = binary("ph2dt")

INP_TEMPLATE = """* ph2dt.inp - generated by run_ph2dt.py (seismic-relocation v1)
* Input station file:
input/station.dat
* Input phase file:
input/phase.dat
*MINWGHT MAXDIST MAXSEP MAXNGH MINLNK MINOBS MAXOBS
   0      {maxdist}      {maxsep}     {maxngh}      {minlnk}      {minobs}     20
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--workdir", required=True)
    ap.add_argument("--maxdist", type=float, default=100)
    ap.add_argument("--maxsep", type=float, default=10)
    ap.add_argument("--maxngh", type=int, default=10)
    ap.add_argument("--minlnk", type=int, default=4)
    ap.add_argument("--minobs", type=int, default=4)
    args = ap.parse_args()
    w = Path(args.workdir)

    h = hashlib.sha256(Path(BIN).read_bytes()).hexdigest()
    if h != EXPECTED_SHA256:
        sys.exit(f"ph2dt sha256 mismatch (R2): {h[:12]}…")

    meta = json.loads((w / "input" / "conversion_meta.json").read_text())
    if meta.get("n_phase_lines", 0) == 0:
        sys.exit("GATE: empty phase.dat (0 phase lines). Refusing to run ph2dt.")

    # R6 fail-closed: independent input verification must exist and match
    ver = w / "input" / "ph2dt_input_verification.json"
    pha = w / "input" / "phase.dat"
    if not ver.exists():
        sys.exit("GATE: run verify_ph2dt_inputs.py first (verification missing).")
    r = json.loads(ver.read_text())
    if r.get("status") != "PASS":
        sys.exit(f"GATE: input verification status={r.get('status')}. Refusing.")
    if r.get("phase_dat_sha256") != hashlib.sha256(pha.read_bytes()).hexdigest():
        sys.exit("GATE: phase.dat changed after verification. Re-run verify_ph2dt_inputs.py.")
    if any((w / prefix / name).exists() for prefix in (".", "input")
           for name in ("dt.ct", "event.dat", "event.sel")):
        sys.exit("GATE: pairing outputs already exist; use a fresh directory for a new pairing experiment")

    (w / "ph2dt.inp").write_text(INP_TEMPLATE.format(
        maxdist=args.maxdist, maxsep=args.maxsep, maxngh=args.maxngh,
        minlnk=args.minlnk, minobs=args.minobs))
    r = subprocess.run([BIN, "ph2dt.inp"], cwd=w, env=native_environment(), capture_output=True, text=True,
                       timeout=3600)
    (w / "ph2dt.log").write_text(r.stdout + r.stderr)
    # ph2dt writes dt.ct / event.dat / event.sel into cwd; collect into input/
    import shutil
    for f in ("dt.ct", "event.dat", "event.sel", "station.sel"):
        src = w / f
        if src.exists():
            shutil.move(str(src), str(w / "input" / f))
    n_dt = sum(1 for l in open(w / "input" / "dt.ct") if l.strip() and not l.startswith("#")) \
        if (w / "input" / "dt.ct").exists() else 0
    status = "FAIL" if r.returncode or not (w / "input/dt.ct").is_file() else ("PASS" if n_dt else "EMPTY")
    (w / "qc").mkdir(exist_ok=True)
    receipt = {"status": status, "exit": r.returncode, "differential_times": n_dt,
               "binary_sha256": h,
               "inputs": {name: sha(w / name) for name in
                          ("input/phase.dat", "input/station.dat", "input/ph2dt_input_verification.json", "ph2dt.inp")},
               "outputs": {"input/" + name: sha(w / "input" / name) for name in ("dt.ct", "event.dat", "event.sel")
                           if (w / "input" / name).is_file()}}
    (w / "qc/pairing_result.json").write_text(json.dumps(receipt, indent=2) + "\n")
    print(f"ph2dt exit={r.returncode}; dt.ct differential times: {n_dt}")
    if status == "FAIL":
        sys.exit("ph2dt failed or omitted its differential-time output")
    if status == "EMPTY":
        print("EMPTY: completed pairing produced no differential observations; this tier needs no solver run")


if __name__ == "__main__":
    main()
