#!/usr/bin/env python3
"""Run pinned hypoDD; the agent selects DAMP from measured spatial evidence.

Modes:
  --damping-trials 20,50,100,200   save spatial evidence, CND, logged RMS and
                                   removals in qc/damping_trials.*
  --damp 50                        final run at the evidence-selected damping
Parses the native log once; reports removals from "negative depth" messages.
Verifies binary sha256 (R2), scientific inputs and final selection evidence.
"""
import argparse
import hashlib
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np

from damping_metrics import RULE_VERSION, displacement_metrics, load_catalog, select_damping
from tier_outcomes import pairing_result

EXPECTED_SHA256 = "f21ce7b4aa0d391d7a32264b89f2288fdbf17919f3d2e44a1b07dcaf8ec7d610"
from contract_io import load_contract
from runtime_support import binary, native_environment
from hypodd_inputs import joint_schedule, verify_joint_receipt
BIN = binary("hypoDD")

INP_TEMPLATE = """* hypoDD.inp - generated by run_hypodd.py (seismic-relocation v1.7)
*--- input files
* cross corr (not used, IDAT=2):

* catalog diff times:
input/dt.ct
* events:
input/event.dat
* stations:
input/station.dat
*--- output files
* original locations:
output/hypoDD.loc
* relocations:
output/hypoDD.reloc
* station info:
output/hypoDD.sta
* residuals:
output/hypoDD.res
* source params:
output/hypoDD.src
* IDAT  IPHA  DIST
  2     3     {dist}
* OBSCC OBSCT
  0     {obsct}
* ISTART ISOLV NSET
  2      2     {nset}
* NITER WTCCP WTCCS WRCC WDCC WTCTP WTCTS WRCT WDCT DAMP
{iter_lines}
* NLAY RATIO
  {nlay}   {ratio}
* TOP
  {top}
* VEL
  {vel}
* CID
  0
* ID
"""

# palm Zherong iteration schedule (catalog-only): loose -> tight
# v1.6: WDCT 末组作为档位轴暴露（--wdct-last；松=4 中=3 严=2）
def iter_lines(damp, wdct_last=3):
    rows = [(4, "-9", "-9", "-9", "-9", "1.0", "0.5", "-9", "-9"),
            (8, "-9", "-9", "-9", "-9", "1.0", "0.5", "6", "5"),
            (12, "-9", "-9", "-9", "-9", "1.0", "0.4", "4", "4"),
            (16, "-9", "-9", "-9", "-9", "1.0", "0.3", "3", str(wdct_last))]
    return "\n".join(
        f"  {n:<4} {a:>4} {b:>4} {c:>4} {d:>4} {e:>5} {f:>5} {g:>4} {h:>4}   {damp}"
        for n, a, b, c, d, e, f, g, h in rows)


def load_cre(path):
    rows = [l.split() for l in Path(path).read_text().splitlines()
            if l.strip() and l.strip()[0].isdigit()]
    arr = np.array(rows, dtype=float)
    return arr[:, 0], arr[:, 1]  # vel, top


def digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def write_json(path, value):
    Path(path).write_text(json.dumps(value, indent=2, allow_nan=False) + "\n")


def parse_log(log):
    number = r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[EeDd][-+]?\d+)?"
    matches = re.findall(r"acond \(CND\)=\s*(" + number + r"); anorm =\s*(" + number
                         + r"); arnorm =\s*(" + number + r")", log)
    rows = [{"cnd": float(c.replace("D", "E").replace("d", "e")),
             "arnorm": float(ar.replace("D", "E").replace("d", "e"))}
            for c, _, ar in matches]
    # Retain the full ordered series. This summary filter is a project convention,
    # not a manual condition or a pass/fail criterion, and may span multiple clusters.
    active = [r["cnd"] for r in rows if r["arnorm"] > 0.01]
    rms = re.findall(r"weighted ct rms \[s\] =\s*(" + number + r")", log)
    rms = [float(x.replace("D", "E").replace("d", "e")) for x in rms]
    return {
        "cnd": active[0] if active else None, "cnd_series": rows,
        "cnd_summary": "first logged record with arnorm > 0.01; diagnostic only",
        "airquakes_removed": len(re.findall(r"negative depth", log, re.I)),
        "rms_last": rms[-1] if rms else None,
        "rms_scope": "last logged weighted catalog RMS; not an all-cluster RMS reduction",
    }


def run_once(w, damp, args, top, vel):
    output = w / "output"
    output.mkdir(exist_ok=True)
    if any(output.iterdir()):
        raise ValueError(f"Run output is not empty: {output}; use a fresh run directory")
    joint = joint_schedule(args.joint_config) if getattr(args, 'joint_config', None) else None
    schedule = iter_lines(damp, args.wdct_last)
    if joint:
        columns = ('niter', 'wtccp', 'wtccs', 'wrcc', 'wdcc', 'wtctp', 'wtcts', 'wrct', 'wdct')
        schedule = '\n'.join('  ' + ' '.join(str(row[k]) for k in columns) + ' ' + str(damp)
                             for row in joint['iterations'])
    inp = INP_TEMPLATE.format(dist=args.dist, obsct=args.obsct, nset=len(joint['iterations']) if joint else 4,
                              iter_lines=schedule, nlay=len(vel),
                              ratio=args.ratio,
                              top=" ".join(f"{z:.2f}" for z in top),
                              vel=" ".join(f"{v:.2f}" for v in vel))
    if joint:
        inp = inp.replace('* cross corr (not used, IDAT=2):\n\n', '* cross correlation:\ninput/dt.cc\n')
        inp = inp.replace('  2     3     ', '  3     3     ')
        inp = inp.replace('  0     ' + str(args.obsct) + '\n',
                          f"  {joint['obscc']}     {joint['obsct']}\n")
    (w / "hypoDD.inp").write_text(inp)
    process = subprocess.run([BIN, "hypoDD.inp"], cwd=w, env=native_environment(), capture_output=True,
                             timeout=7200)
    stdout = (process.stdout + process.stderr).decode("utf-8", errors="replace")
    (w / "stdout.log").write_text(stdout)
    logfile = w / "hypoDD.log"
    # The native log and stdout overlap: concatenation doubles removal counts.
    log = logfile.read_bytes().decode("utf-8", errors="replace") if logfile.exists() else stdout
    result = {"damp": damp, **parse_log(log), "exit": process.returncode,
              "status": "FAIL", "run_dir": str(w), "centroid_shift_km": None}
    if process.returncode:
        result["error"] = "hypoDD exited with a nonzero status"
        return result
    paths = {"initial": output / "hypoDD.loc", "relocated": output / "hypoDD.reloc"}
    if any(not p.exists() for p in paths.values()):
        result["error"] = "hypoDD did not produce both location files"
        return result
    initial, relocated = load_catalog(paths["initial"]), load_catalog(paths["relocated"])
    result.update(n_input=len(initial), n_relocated=len(relocated),
                  artifacts={k: {"path": str(p), "sha256": digest(p)} for k, p in paths.items()})
    if not relocated:
        result.update(status="EMPTY", reason="NO_RELOCATED_EVENTS")
        return result
    if joint:
        counts = {'cc': 0, 'ct': 0}
        by_cluster = {}
        for line in paths['relocated'].read_text().splitlines():
            f = line.split()
            if not f:
                continue
            if len(f) != 24:
                raise ValueError('Joint solve needs native per-event CC/CT counts')
            cc, ct = sum(map(int, f[17:19])), sum(map(int, f[19:21]))
            counts['cc'] += cc; counts['ct'] += ct
            cluster = by_cluster.setdefault(f[-1], {'cc': 0, 'ct': 0})
            cluster['cc'] += cc; cluster['ct'] += ct
        result.update(data_mode='cc_ct', used_event_observation_counts=counts,
                      counts_scope='sum of retained-event incidences, not unique differential observations',
                      used_counts_by_cluster=by_cluster)
        if not counts['cc'] or not counts['ct']:
            result['error'] = 'Joint run did not retain both CC and CT constraints'
            return result
    result.update(displacement_metrics(initial, relocated), status="PASS")
    return result


def trial_context(w, args):
    paths = [w / "input" / name for name in ("dt.ct", "event.dat", "station.dat")]
    joint = getattr(args, 'joint_config', None)
    if joint:
        if Path(joint).resolve() != (w / 'input/joint_config.json').resolve():
            raise ValueError('Joint configuration must be in the verified input bundle')
        joint_schedule(joint)
        verify_joint_receipt(w / 'input')
        paths += [w / 'input' / name for name in ('dt.cc', 'joint_config.json', 'joint_verification.json')]
    if any(not p.is_file() or p.stat().st_size == 0 for p in paths):
        raise ValueError("GATE: input/dt.ct, event.dat and station.dat must be nonempty")
    context = {
        "rule_version": RULE_VERSION, "binary_sha256": digest(BIN),
        "runner_sha256": digest(__file__),
        "metrics_sha256": digest(Path(__file__).with_name("damping_metrics.py")),
        "input_sha256": {p.name: digest(p) for p in paths},
        "vp_model_sha256": digest(args.vp_model),
        "ratio": args.ratio, "dist": args.dist, "obsct": args.obsct,
        "wdct_last": args.wdct_last, "initial_erh_km": args.initial_erh_km,
    }
    if joint:
        context['data_mode'] = 'cc_ct'
        context['joint_validator_sha256'] = digest(__import__('hypodd_inputs').__file__)
    return context


def plot_trials(selection, destination):
    import matplotlib
    matplotlib.use("agg")
    import matplotlib.pyplot as plt
    results = selection["per_trial"]
    ds = [r["damp"] for r in results]
    values = lambda name: [r.get(name) if r.get(name) is not None else np.nan for r in results]
    fig, axes = plt.subplots(2, 2, figsize=(11, 8))
    axes = axes.ravel()
    axes[0].plot(ds, values("cnd"), "o-")
    axes[0].axhspan(40, 80, color="g", alpha=0.15, label="empirical reference 40-80")
    axes[0].set_ylabel("CND: first active log record")
    axes[1].plot(ds, values("rms_last"), "o-", label="last logged weighted catalog RMS")
    axes[1].set_ylabel("RMS (s; not an all-cluster statistic)")
    axes[2].plot(ds, values("centroid_shift_km"), "o-", label="maximum cluster centroid shift")
    axes[2].plot(ds, values("event_displacement_median_km"), "s--", label="median event displacement")
    axes[2].axhline(selection["initial_erh_km"], color="r", linestyle=":", label="project ERH scale")
    axes[2].set_ylabel("Displacement (km)")
    axes[3].plot(ds, [r["structure"].get("struct_diff_km", np.nan) for r in results], "o-",
                 label="centered structure vs next larger DAMP")
    axes[3].axhline(selection["initial_erh_km"], color="r", linestyle=":", label="project ERH scale")
    axes[3].set_ylabel("Structure difference (km)")
    for axis in axes:
        axis.set_xscale("log")
        axis.set_xlabel("DAMP")
        axis.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(destination, dpi=160)
    plt.close(fig)


def validate_final_selection(qc, context, damp):
    selection = json.loads((qc / "damping_selection.json").read_text())
    if selection.get("rule_version") != RULE_VERSION or selection.get("context") != context:
        raise ValueError("GATE: stale damping evidence; rerun trials with current inputs/configuration")
    if selection.get("status") != "SELECTED" or selection.get("selected_damp") != damp:
        raise ValueError("GATE: final DAMP must match the supported selection; unresolved trials need review")
    results = json.loads((qc / "damping_trials.json").read_text())
    if results != selection.get("per_trial"):
        raise ValueError("GATE: damping trial and selection records disagree")
    catalogs = {}
    for result in results:
        if result.get("status") != "PASS":
            continue
        artifacts = result["artifacts"]
        for item in artifacts.values():
            if digest(item["path"]) != item["sha256"]:
                raise ValueError("GATE: trial artifact changed")
        initial = load_catalog(artifacts["initial"]["path"])
        relocated = load_catalog(artifacts["relocated"]["path"])
        metrics = displacement_metrics(initial, relocated)
        if any(result.get(k) != value for k, value in metrics.items()):
            raise ValueError("GATE: trial spatial metrics disagree with saved locations")
        catalogs[result["damp"]] = relocated
    recomputed = select_damping(results, catalogs, context["initial_erh_km"])
    if recomputed["selected_damp"] != damp or recomputed["per_trial"] != results:
        raise ValueError("GATE: saved DAMP is not supported by the trial evidence")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--workdir", required=True)
    ap.add_argument('--joint-config', help='Verified input/joint_config.json enables CC+CT IDAT=3')
    ap.add_argument("--vp-model", required=True)
    ap.add_argument("--ratio", type=float, required=True, help="measured Wadati Vp/Vs")
    ap.add_argument("--dist", type=float, default=100)
    ap.add_argument("--obsct", type=int, default=4)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--damping-trials", help="distinct positive values, e.g. 20,50,100,200")
    mode.add_argument("--damp", type=float, help="final run at the evidence-selected damping")
    ap.add_argument("--initial-erh-km", type=float, required=True,
                    help="measured initial median ERH; project spatial comparison scale, not a 3-D error bound")
    ap.add_argument("--wdct-last", type=float, default=3,
                    help="final WDCT km: loose=4, medium=3, strict=2")
    args = ap.parse_args()
    for name in ("ratio", "dist", "initial_erh_km", "wdct_last"):
        if not np.isfinite(getattr(args, name)) or getattr(args, name) <= 0:
            ap.error(f"--{name.replace('_', '-')} must be finite and positive")
    if args.obsct < 1:
        ap.error("--obsct must be positive")
    if digest(BIN) != EXPECTED_SHA256:
        raise ValueError("hypoDD sha256 mismatch (R2)")
    w = Path(args.workdir).resolve()
    pair = pairing_result(w)
    if pair is not None and pair["status"] == "FAIL":
        raise ValueError("Pairing failed; refusing to run the solver")
    if pair is not None and pair["status"] == "EMPTY":
        print("EMPTY: verified pairing contains no observations; no DAMP is selected")
        return
    context = trial_context(w, args)
    vel, top = load_cre(args.vp_model)
    qc = w / "qc"
    if args.damping_trials:
        trials = sorted(float(x) for x in args.damping_trials.split(","))
        if len(trials) < 2 or len(set(trials)) != len(trials):
            ap.error("Provide at least two distinct damping candidates")
        if any(not np.isfinite(d) or d <= 0 for d in trials):
            ap.error("Damping candidates must be finite and positive")
        qc.mkdir(exist_ok=True)
        batch = Path(tempfile.mkdtemp(prefix="damping_runs_", dir=qc))
        results, catalogs = [], {}
        for damp in trials:
            trial = batch / ("damp_" + format(damp, ".17g"))
            trial.mkdir()
            (trial / "input").symlink_to(w / "input", target_is_directory=True)
            print(f"[trial] DAMP={damp}", flush=True)
            try:
                result = run_once(trial, damp, args, top, vel)
                if result["status"] == "PASS":
                    catalogs[damp] = load_catalog(result["artifacts"]["relocated"]["path"])
            except (ValueError, OSError, subprocess.TimeoutExpired) as exc:
                result = {"damp": damp, "status": "FAIL", "run_dir": str(trial),
                          "error": str(exc), "centroid_shift_km": None}
            results.append(result)
            print(f"  {result['status']}; relocated={result.get('n_relocated', 0)}", flush=True)
        if trial_context(w, args) != context:
            raise ValueError("GATE: inputs/configuration changed during damping trials")
        selection = select_damping(results, catalogs, args.initial_erh_km)
        if results and all(r["status"] == "EMPTY" for r in results):
            selection.update(status="EMPTY", reason="NO_RELOCATED_EVENTS_IN_TRIALS")
        selection["context"] = context
        write_json(qc / "damping_trials.json", selection["per_trial"])
        try:
            plot_trials(selection, qc / "damping_trials.png")
            selection["plot_status"] = "PASS"
        except Exception as exc:
            selection.update(plot_status="FAIL", plot_error=str(exc))
            if (qc / "damping_trials.png").exists():
                (qc / "damping_trials.png").unlink()
        write_json(qc / "damping_selection.json", selection)
        print(json.dumps({k: selection[k] for k in ("status", "plateau", "selected_damp")}))
        return
    if not np.isfinite(args.damp) or args.damp <= 0:
        ap.error("--damp must be finite and positive")
    validate_final_selection(qc, context, args.damp)
    result = run_once(w, args.damp, args, top, vel)
    write_json(qc / "final_run.json", result)
    if result["status"] != "PASS":
        raise ValueError("Final hypoDD run failed; see qc/final_run.json")
    print(f"final run DAMP={args.damp}: relocated={result['n_relocated']}")


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError, KeyError, subprocess.TimeoutExpired) as exc:
        sys.exit(str(exc))
