#!/usr/bin/env python3
"""Drive pinned hyp1.40 over a prepared input/ directory (R2 enforced).

- Verifies the binary sha256 before running.
- Generates the command file from anchored defaults (SKILL.md sec.2);
  PRT/SUM/ARC explicitly opened (default NONE trap).
- Answers interactive prompts with carriage returns (official testone pattern).
- Scans .prt for '***' error lines and remark codes.
"""
import argparse
import hashlib
import subprocess
import sys
from pathlib import Path

EXPECTED_SHA256 = "892f465a5de16c4fdee47f1fd2e06aa76a4c8f9fb3001638fa014f0e3827a5c2"
from contract_io import load_contract
from runtime_support import binary, native_environment
BIN = binary("hyp1.40")


def check_binary():
    h = hashlib.sha256(Path(BIN).read_bytes()).hexdigest()
    if h != EXPECTED_SHA256:
        sys.exit(f"binary sha256 mismatch: {h[:16]}… expected {EXPECTED_SHA256[:16]}… "
                 "(R2: only the pinned golden-tested build may run)")
    return h


def write_command_file(workdir: Path, s_model: bool, pos: float):
    cmds = [
        "* generated by run_hypoinverse.py (seismic-location v1)",
        "LET 5 2 3 2 2",
        "RMS 4 .10 2 3",
        "ERR .10",
        f"POS {pos:.2f}",
        "MIN 4",
        "ZTR 5 F",
        "DI1 1 50 3 6",
        "DIS 4 15 3.5 7",
        "WET 1. .5 .2 .1",
        "ERF T", "TOP F", "KPR 2", "H71 4 1 3",
        "STA 'input/stations.sta'",
        "CRH 1 'input/p.crh'",
    ]
    if s_model:
        cmds += ["CRH 2 'input/s.crh'", "SAL 1 2"]
    cmds += [
        "PHS 'input/phase.dat'", "FIL",
        "PRT 'output/run.prt'", "SUM 'output/run.sum'", "ARC 'output/run.arc'",
    ]
    (workdir / "run.hyp").write_text("\n".join(cmds) + "\n", encoding="utf-8")


def check_verification_gate(w: Path):
    """Fail-closed: refuse to run unless the product verifier passed on the
    CURRENT phase.dat (verification must be newer than the input)."""
    ver = w / "input" / "phase_dat_verification.json"
    pha = w / "input" / "phase.dat"
    if not ver.exists():
        sys.exit("GATE: phase_dat_verification.json missing -- run verify_phase_dat.py first. "
                 "Refusing to locate unverified input.")
    import json as _json
    r = _json.loads(ver.read_text())
    if r.get("status") != "PASS":
        sys.exit(f"GATE: verification status={r.get('status')}. Refusing to run.")
    import hashlib as _hl
    actual = _hl.sha256(pha.read_bytes()).hexdigest()
    if r.get("phase_dat_sha256") != actual:
        sys.exit("GATE: verification was made for a different phase.dat (hash mismatch). "
                 "Re-run verify_phase_dat.py -- forged or stale verification refused.")
    if ver.stat().st_mtime < pha.stat().st_mtime:
        sys.exit("GATE: phase.dat is newer than its verification -- re-run verify_phase_dat.py.")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--workdir", required=True, help="dir containing input/")
    args = ap.parse_args()
    w = Path(args.workdir)
    (w / "output").mkdir(exist_ok=True)

    check_verification_gate(w)   # fail-closed; agent cannot skip verification
    sha = check_binary()
    meta = __import__("json").loads((w / "input" / "conversion_meta.json").read_text())
    write_command_file(w, meta["s_model"], meta["pos"])

    stdin = "\n".join(["@run.hyp"] + [""] * 40 + ["loc", "stop"]) + "\n"
    with open(w / "output" / "run.stdout.log", "w") as log:
        r = subprocess.run([BIN], cwd=w, env=native_environment(), input=stdin, stdout=log,
                           stderr=subprocess.STDOUT, text=True, timeout=3600)
    prt = (w / "output" / "run.prt").read_text(errors="replace")
    if r.returncode:
        sys.exit(f"HYPOINVERSE failed with exit code {r.returncode}; see output/run.stdout.log")
    if any(not (w / "output" / ("run." + ext)).is_file() for ext in ("sum", "arc", "prt")):
        sys.exit("HYPOINVERSE did not produce all required outputs")
    errs = [l for l in prt.splitlines() if l.lstrip().startswith("***")]  # prt 错误行有前导空格
    print(f"binary sha256 ok ({sha[:12]}…); exit={r.returncode}; "
          f"*** error lines in prt: {len(errs)}")
    for l in errs[:10]:
        print(l)
    print(f"outputs: {w/'output'}/run.{{sum,arc,prt}}")


if __name__ == "__main__":
    main()
